
services:
  - type: web
    name: aviator-bantubet
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
